version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    command: sh -c "yarn typeorm:cli migration:run && yarn start"
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
